name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_VERBOSE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run mise check
        run: |
          mise run check

  lint:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable@sha256:1f872881165d42cc34e9404c50c481bc5cf9229c4159fcee4788fb8ee09e4ca7
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_VERBOSE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run mise lint
        run: |
          mise run lint

  test:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_VERBOSE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run mise test
        run: |
          mise run test

  build:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_VERBOSE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run mise build (release)
        run: |
          mise run build:release
