name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable@sha256:343c04995cff365190a252748e9d11623721f8c23627b5ec075328b21f580fb6
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_VERBOSE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install mise tools
        run: mise install --verbose

      - name: Mise ls
        run: |
          mise ls

      - name: Run mise lint
        run: |
          mise run lint
