name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable@sha256:6512d669748240e9f34bc9853b2f13ceffda4030c62b58216d7710c16573b600
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_VERBOSE: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install mise tools
        run: mise install --verbose

      - name: Mise ls
        run: |
          mise ls

      - name: Run mise lint
        run: |
          mise run lint
