name: Security

on:
  push:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable@sha256:6a4355529245d9de528032a15a9cd806c9fa30b7a3cd99565252d5c36817ba46
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install mise tools
        run: |
          mise install

      - name: Run gitleaks
        run: |
          gitleaks detect --source="${GITHUB_WORKSPACE}" --no-git
