name: Security

on:
  push:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:gazelle-b55a6ea72f8718d651d0f9e98e5cc5d52942021f
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Install mise tools
        run: |
          mise install

      - name: Run gitleaks
        run: |
          gitleaks detect --source="${GITHUB_WORKSPACE}" --no-git
