name: Security

on:
  push:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: colinyates/dev-docker:stable@sha256:7cbb5bd0b63a3d585df7b1eb9c03516d8653902e5822e11106f80f7e32a767b1
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      MISE_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install mise tools
        run: |
          mise install

      - name: Run gitleaks
        run: |
          gitleaks detect --source="${GITHUB_WORKSPACE}" --no-git
